dist: xenial
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-7
            - clang-9
            - clang-tidy-9
            - clang-format-9
              # dependencies for conan
            - python3 
            - python3-pip 
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-7
            - clang-9
            - clang-tidy-9
            - clang-format-9
              # dependencies for conan
            - python3
            - python3-pip
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./travis.sh
