language: cpp

os: linux
dist: xenial

packages:
    # conan dependencies
    - python3
    - python3-pip
    - python3-setuptools

install:
    # install conan
    - pip3 install conan
    - conan profile update settings.compiler.libcxx=libstdc++11 default

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
              #it would make sense to test with standard libraries acommpanying 
              #all other compiler versions => let's not abuse free CPUs
              #gcc-7 is currently default in Ubuntu 18.04
            - g++-7 
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./travis.sh

