dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-9
            # Support for Conan dependency management
            - python3
            - python3-pip
            - python3-setuptools
            # Clang tools
            - clang-format-10
            - clang-tidy-10
      install:
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            # Support for Conan dependency management
            - python3
            - python3-pip
            - python3-setuptools
            # Clang tools
            - clang-format-10
            - clang-tidy-10
      install:
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./ci/travis.sh

