language: cpp

dist: xenial

matrix:
  include:
    - os: linux   
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            # conan dependencies
            - python3
            - python3-pip
            - python3-setuptools 
      install:
          - pip3 install conan
          - conan profile update settings.compiler.libcxx=libstdc++11 default
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux   
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            # conan dependencies
            - python3
            - python3-pip
            - python3-setuptools
      install:
          - pip3 install conan
          - conan profile update settings.compiler.libcxx=libstdc++11 default
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - addons:
    - os: linux   
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            # conan dependencies
            - python3
            - python3-pip
            - python3-setuptools
      install:
          - pip3 install conan
          - conan profile update settings.compiler.libcxx=libstdc++11 default
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux   
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
              #it would make sense to test with standard libraries acommpanying 
              #all other compiler versions => let's not abuse free CPUs
              #gcc-7 is currently default in Ubuntu 18.04
            - g++-7 
            - clang-8
            # conan dependencies
            - python3
            - python3-pip
            - python3-setuptools
      install:
          - pip3 install conan
          - conan profile update settings.compiler.libcxx=libstdc++11 default
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./travis.sh

