dist: xenial
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
              # dependencies for conan
            - python3 
            - python3-pip 
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
              # dependencies for conan
            - python3
            - python3-pip
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
              # dependencies for conan
            - python3
            - python3-pip
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-8
              # dependencies for conan
            - python3
            - python3-pip
            - python3-setuptools
      install:
          # install conan
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./travis.sh

