dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - g++-10
            # Support for Conan dependency management
            - python3
            - python3-pip
            - python3-setuptools
            # Clang tools
            - clang-format-10
            - clang-tidy-10
            # Build tools
            - cmake
      install:
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - clang-10
            # Standard library
            - g++-10
            # Support for Conan dependency management
            - python3
            - python3-pip
            - python3-setuptools
            # Clang tools
            - clang-format-10
            - clang-tidy-10
            # Build tools
            - cmake
      install:
          - pip3 install conan
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./ci/travis.sh

