# Executables
install(TARGETS 
    mdbsrv 
    mclxmp
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        COMPONENT ${PROJECT}_rt
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT ${PROJECT}_rt
        NAMELINK_COMPONENT ${PROJECT}_dev
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT ${PROJECT}_dev
)

# Shared libraries
install(TARGETS 
    mdbnet 
    mbltrc
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        COMPONENT ${PROJECT}_rt
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT ${PROJECT}_rt
        NAMELINK_COMPONENT ${PROJECT}_dev
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        COMPONENT ${PROJECT}_dev
)
